module.exports = {
    BaseService: require('./Base.service'),
    BDService: require('./BD.service'),
    ADService: require('./AD.service'),
    AuthService: require('./Auth.service'),
    PerifericoService: require('./Periferico.service'),
    EquipoService: require('./Equipo.service'),
    AsignacionService: require('./Asignacion.service'),
    MantenimientoService: require('./Mantenimiento.service'),
    FileService: require('./File.service'),
    DetalleMantService: require('./DetalleMant.service'),
    SistemaOperativoService: require('./SistemaOperativo.service'),
    FabricanteService: require('./Fabricante.service'),
    ActividadService: require('./Actividad.service'),
    TecnicoService: require('./Tecnico.service'),
}