module.exports = {
    BDrepository: require('./BD.repository'),
    BaseRepository: require('./base.repository'),
    AdRepository: require('./AD.repository'),
    PerifericoRepository: require('./Perifericos.repository'),
    EquipoRepository: require('./Equipo.repository'),
    AsignacionRepository: require('./Asignacion.repository'),
    MantenimientoRepository: require('./Mantenimiento.repository'),
    FileRepository: require('./File.repository'),
    DetalleMantRepository: require('./DetalleMant.repository'),
    SistemaOperativoRepository: require('./SistemaOperativo.repository'),
    FabricanteRepository: require('./Fabricante.repository'),
    ActividadRepository: require('./Actividad.repository'),
    TecnicoRepository: require('./Tecnico.repository'),
    ModeloRepository: require('./Modelo.repository'),
}